// XFILE.h: interface for the XFILE class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_XFILE_H__A3665584_7B86_4226_A328_45972C0D04B6__INCLUDED_)
#define AFX_XFILE_H__A3665584_7B86_4226_A328_45972C0D04B6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class XFILE  
{
public:
	XFILE();
	virtual ~XFILE();

};

#endif // !defined(AFX_XFILE_H__A3665584_7B86_4226_A328_45972C0D04B6__INCLUDED_)
